### ISSUE TITLE
The mapper function returned a null value.

### ISSUE THREAD

**Issue by developeromI89** [matthiasbruns/RxRetrofit#1]
E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                Process: com.example.admin1.testnewstudio, PID: 5956
                                                                                io.reactivex.exceptions.OnErrorNotImplementedException: The mapper function returned a null value.
                                                                                    at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:704)
                                                                                    at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:701)
                                                                                    at io.reactivex.internal.observers.ConsumerSingleObserver.onError(ConsumerSingleObserver.java:47)
                                                                                    at io.reactivex.internal.operators.single.SingleMap$MapSingleObserver.onError(SingleMap.java:69)
                                                                                    at io.reactivex.internal.operators.single.SingleMap$MapSingleObserver.onSuccess(SingleMap.java:60)
                                                                                    at io.reactivex.internal.operators.single.SingleObserveOn$ObserveOnSingleObserver.run(SingleObserveOn.java:81)
                                                                                    at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:109)
                                                                                    at android.os.Handler.handleCallback(Handler.java:739)
                                                                                    at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                    at android.os.Looper.loop(Looper.java:135)
                                                                                    at android.app.ActivityThread.main(ActivityThread.java:5268)
                                                                                    at java.lang.reflect.Method.invoke(Native Method)
                                                                                    at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:902)
                                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:697)
                                                                                 Caused by: java.lang.NullPointerException: The mapper function returned a null value.
                                                                                    at io.reactivex.internal.functions.ObjectHelper.requireNonNull(ObjectHelper.java:39)
                                                                                    at io.reactivex.internal.operators.single.SingleMap$MapSingleObserver.onSuccess(SingleMap

**Comment by rickAllDev** [comment]
same issue here with the demo code. To correct, paste in url example and you get message indicating demo account has exceeded credits. I created new demo account, activated free web services, changed the value of username in RetrofitHelper class and everything works fine.

**Comment by BismeetSingh** [comment]
OnErrorNotImplementedException.
